packages:
  - 'packages/@endge-nova'
  - '../../packages/@endge-codegen'
  - '../../packages/@endge-core'
  - '../../packages/@endge-raph'
  - '../../packages/@endge-utils'
  - '../../packages/@endge-vue'
