packages:
  - '../../packages/@endge-codegen'
  - '../../packages/@endge-core'
  - '../../packages/@endge-computation-sandbox'
  - '../../packages/@endge-raph'
  - '../../packages/@endge-utils'
  - '../../packages/@endge-ui-vue'
allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  ttf2woff2: set this to true or false
  vue-demi: set this to true or false
