import type { DocumentCreateDescriptor } from '@/features/endge-ide/domain/types/document-create.type'

import { ComponentType, DomainSectionType, FilterType, QueryType } from '@endge/core'

import { QUERY_COMPOSITION_CREATE_KIND } from '@/features/endge-ide/model/domain/query-composition-presentation'

/** Source нового Table Component: тот же SFC-документ, но сразу с визуально редактируемым Table root. */
export const COMPONENT_TABLE_SFC_DEFAULT_SOURCE = `<script setup lang="ts">
</script>

<template>
  <Table />
</template>

<style lang="endgecss" scoped>
</style>
`

export const DOCUMENT_CREATE_DESCRIPTORS: DocumentCreateDescriptor[] = [
  {
    type: ComponentType.SFC,
    label: 'Компонент',
    description: 'Source-first компонент с template, script и style в одном документе.',
    keywords: ['component', 'source', 'template', 'sfc', 'компонент'],
    defaultName: 'Новый компонент',
    section: DomainSectionType.Component,
    group: 'Компоненты',
    supportsFolder: true,
    supportsDescription: false,
  },
  {
    type: ComponentType.Table,
    label: 'Table Component',
    description: 'Single-file компонент с заранее добавленным корневым Table-тегом.',
    keywords: ['component', 'table', 'columns', 'таблица', 'sfc'],
    defaultName: 'Новый Table Component',
    section: DomainSectionType.Component,
    group: 'Компоненты',
    supportsFolder: true,
    supportsDescription: false,
  },
  {
    type: 'type',
    label: 'Тип',
    description: 'Переиспользуемое описание структуры данных и её полей.',
    keywords: ['type', 'schema', 'model', 'модель'],
    defaultName: 'Новый тип',
    section: DomainSectionType.Type,
    group: 'Данные',
    supportsFolder: true,
    supportsDescription: false,
  },
  {
    type: QueryType.REST,
    label: 'Запрос',
    description: 'Source-first запрос к внешнему или внутреннему источнику данных.',
    keywords: ['query', 'rest', 'api', 'данные'],
    defaultName: 'Новый запрос',
    section: DomainSectionType.Query,
    group: 'Данные',
    supportsFolder: true,
    supportsDescription: false,
  },
  {
    type: QUERY_COMPOSITION_CREATE_KIND,
    label: 'Композиция запросов',
    description: 'Композиция, представленная в разделе запросов и сохраняемая с query-role.',
    keywords: ['query', 'composition', 'pipeline', 'композиция'],
    defaultName: 'Новая композиция',
    section: DomainSectionType.Query,
    group: 'Данные',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: 'data-view',
    label: 'Data View',
    description: 'Представление данных, которое связывает источники, связи и projections.',
    keywords: ['data', 'view', 'projection', 'представление'],
    defaultName: 'Новый Data View',
    section: DomainSectionType.DataView,
    group: 'Данные',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: 'store',
    label: 'Хранилище',
    description: 'Source-first описание состояния и его начальных значений.',
    keywords: ['store', 'state', 'состояние'],
    defaultName: 'Новое хранилище',
    section: DomainSectionType.Store,
    group: 'Данные',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: 'mock',
    label: 'Mock',
    description: 'Тестовый JSON или text payload для локальной разработки и preview.',
    keywords: ['mock', 'fixture', 'json', 'тестовые данные'],
    defaultName: 'Новый Mock',
    section: DomainSectionType.Mock,
    group: 'Данные',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: FilterType.DefaultFilter,
    label: 'Фильтр',
    description: 'Описание фильтруемых полей и source поведения Filter Runtime.',
    keywords: ['filter', 'fields', 'фильтр'],
    defaultName: 'Новый фильтр',
    section: DomainSectionType.Filters,
    group: 'Данные',
    supportsFolder: true,
    supportsDescription: false,
  },
  {
    type: 'composition',
    label: 'Композиция',
    description: 'Source-first сборка компонентов, stores, queries и других runtime resources.',
    keywords: ['composition', 'runtime', 'layout', 'композиция'],
    defaultName: 'Новая композиция',
    section: DomainSectionType.Composition,
    group: 'Логика',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: 'action',
    label: 'Действие',
    description: 'Исполняемый flow с nodes, edges, input и output contract.',
    keywords: ['action', 'flow', 'workflow', 'действие'],
    defaultName: 'Новое действие',
    section: DomainSectionType.Action,
    group: 'Логика',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: 'computation',
    label: 'Вычисление',
    description: 'Source-first вычисление с явными input и output contracts.',
    keywords: ['computation', 'function', 'calculate', 'вычисление'],
    defaultName: 'Новое вычисление',
    section: DomainSectionType.Computation,
    group: 'Логика',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: 'style',
    label: 'Стиль',
    description: 'Renderer-neutral presentation rules и visual tokens приложения.',
    keywords: ['style', 'theme', 'presentation', 'стиль'],
    defaultName: 'Новый стиль',
    section: DomainSectionType.Style,
    group: 'Интерфейс',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: 'page-template',
    label: 'Шаблон страницы',
    description: 'Структура областей и layout, которую используют страницы.',
    keywords: ['page', 'template', 'layout', 'шаблон'],
    defaultName: 'Новый шаблон страницы',
    section: DomainSectionType.PageTemplate,
    group: 'Интерфейс',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: 'page',
    label: 'Страница',
    description: 'Маршрут приложения, связанный с шаблоном и наполнением его областей.',
    keywords: ['page', 'route', 'screen', 'страница'],
    defaultName: 'Новая страница',
    section: DomainSectionType.Page,
    group: 'Интерфейс',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: 'navigation',
    label: 'Навигация',
    description: 'Дерево пунктов навигации, маршрутов и внешних ссылок.',
    keywords: ['navigation', 'menu', 'route', 'навигация'],
    defaultName: 'Новая навигация',
    section: DomainSectionType.Navigation,
    group: 'Интерфейс',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: 'vocabs',
    label: 'Словарь',
    description: 'Внутренний или внешний справочник значений для доменных полей.',
    keywords: ['vocab', 'dictionary', 'справочник', 'словарь'],
    defaultName: 'Новый словарь',
    section: DomainSectionType.Vocabs,
    group: 'Интерфейс',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: 'i18n-bundles',
    label: 'Словарь переводов',
    description: 'Набор локализованных сообщений для поддерживаемых языков.',
    keywords: ['i18n', 'locale', 'translation', 'переводы'],
    defaultName: 'Новый словарь переводов',
    section: DomainSectionType.I18nBundles,
    group: 'Интерфейс',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: 'integration',
    label: 'Интеграция',
    description: 'Декларация внешней интеграции и её management metadata.',
    keywords: ['integration', 'external', 'интеграция'],
    defaultName: 'Новая интеграция',
    section: DomainSectionType.Integration,
    group: 'Система',
    supportsFolder: false,
    supportsDescription: true,
  },
  {
    type: 'environment',
    label: 'Окружение',
    description: 'Configuration contribution для конкретного runtime environment.',
    keywords: ['environment', 'configuration', 'окружение'],
    defaultName: 'Новое окружение',
    section: DomainSectionType.Environment,
    group: 'Система',
    supportsFolder: true,
    supportsDescription: false,
  },
  {
    type: 'tenant',
    label: 'Тенант',
    description: 'Tenant-level configuration и стабильный code организации.',
    keywords: ['tenant', 'organization', 'тенант'],
    defaultName: 'Новый тенант',
    section: DomainSectionType.Tenant,
    group: 'Система',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: 'policy',
    label: 'Политика',
    description: 'Декларация правил и ограничений, применяемых системой.',
    keywords: ['policy', 'rules', 'security', 'политика'],
    defaultName: 'Новая политика',
    section: DomainSectionType.Policy,
    group: 'Система',
    supportsFolder: true,
    supportsDescription: true,
  },
  {
    type: 'auth-profile',
    label: 'Профиль авторизации',
    description: 'Настройки auth adapter и ссылки на credentials без хранения секретов в документе.',
    keywords: ['auth', 'profile', 'keycloak', 'авторизация'],
    defaultName: 'Новый профиль авторизации',
    section: DomainSectionType.AuthProfile,
    group: 'Система',
    supportsFolder: true,
    supportsDescription: true,
  },
]
