import type { EndgeAdminFlowBlockSpec } from '@/features/endge-admin/domain/action-flow/endge-admin-flow-catalog.types'

export const ENDGE_ADMIN_ACTION_FLOW_DEFAULT_BLOCKS: EndgeAdminFlowBlockSpec[] = [
  {
    id: 'core.start',
    title: 'Start',
    description: 'Точка входа потока.',
    kind: 'start',
    configurable: false,
    inputPorts: [],
    outputPorts: [{ id: 'out', label: 'Далее', direction: 'output', multiple: false, required: false, valueType: null }],
    meta: {},
  },
  {
    id: 'core.watch',
    title: 'Подписка на хранилище',
    description: 'Подписка на изменения по путям Raph/Store.',
    kind: 'watch',
    configurable: true,
    inputPorts: [],
    outputPorts: [{ id: 'out', label: 'Далее', direction: 'output', multiple: false, required: false, valueType: null }],
    meta: {},
  },
  {
    id: 'core.event-subscribe',
    title: 'Подписка на событие',
    description: 'Подписка на системные ивенты приложения.',
    kind: 'eventSubscribe',
    configurable: true,
    inputPorts: [],
    outputPorts: [{ id: 'out', label: 'Далее', direction: 'output', multiple: false, required: false, valueType: null }],
    meta: {},
  },
  {
    id: 'core.delay',
    title: 'Задержка',
    description: 'Пауза перед продолжением потока.',
    kind: 'delay',
    configurable: true,
    inputPorts: [],
    outputPorts: [{ id: 'out', label: 'Далее', direction: 'output', multiple: false, required: false, valueType: null }],
    meta: {},
  },
  {
    id: 'core.timer',
    title: 'Таймер',
    description: 'Ожидание по таймеру перед продолжением потока.',
    kind: 'timer',
    configurable: true,
    inputPorts: [],
    outputPorts: [{ id: 'out', label: 'Далее', direction: 'output', multiple: false, required: false, valueType: null }],
    meta: {},
  },
  {
    id: 'core.interval-timer',
    title: 'Интервальный таймер',
    description: 'Периодический таймер для повторного запуска ветки.',
    kind: 'intervalTimer',
    configurable: true,
    inputPorts: [],
    outputPorts: [{ id: 'out', label: 'Далее', direction: 'output', multiple: false, required: false, valueType: null }],
    meta: {},
  },
  {
    id: 'core.action',
    title: 'Action',
    description: 'Исполняемое действие из домена.',
    kind: 'action',
    configurable: true,
    inputPorts: [{ id: 'in', label: 'Вход', direction: 'input', multiple: false, required: true, valueType: null }],
    outputPorts: [{ id: 'success', label: 'Успех', direction: 'output', multiple: false, required: false, valueType: null }],
    meta: {},
  },
  {
    id: 'core.query',
    title: 'Запрос',
    description: 'Исполняемый запрос из домена.',
    kind: 'query',
    configurable: true,
    inputPorts: [{ id: 'in', label: 'Вход', direction: 'input', multiple: false, required: true, valueType: null }],
    outputPorts: [{ id: 'success', label: 'Успех', direction: 'output', multiple: false, required: false, valueType: null }],
    meta: {},
  },
  {
    id: 'core.runtime-action',
    title: 'Действие (управляемое)',
    description: 'Шаг, подключаемый кодом по runtime id.',
    kind: 'runtimeAction',
    configurable: true,
    inputPorts: [{ id: 'in', label: 'Вход', direction: 'input', multiple: false, required: true, valueType: null }],
    outputPorts: [{ id: 'success', label: 'Успех', direction: 'output', multiple: false, required: false, valueType: null }],
    meta: {},
  },
  {
    id: 'core.switch',
    title: 'Switch',
    description: 'Ветвление по условиям.',
    kind: 'switch',
    configurable: true,
    inputPorts: [{ id: 'in', label: 'Вход', direction: 'input', multiple: false, required: true, valueType: null }],
    outputPorts: [
      { id: 'case-1', label: 'Условие 1', direction: 'output', multiple: false, required: false, valueType: null },
      { id: 'else', label: 'Иначе', direction: 'output', multiple: false, required: false, valueType: null },
    ],
    meta: {},
  },
  {
    id: 'core.forEach',
    title: 'For Each',
    description: 'Цикл по коллекции.',
    kind: 'forEach',
    configurable: true,
    inputPorts: [{ id: 'in', label: 'Вход', direction: 'input', multiple: false, required: true, valueType: null }],
    outputPorts: [
      { id: 'loop', label: 'Цикл', direction: 'output', multiple: false, required: false, valueType: null },
      { id: 'done', label: 'Завершено', direction: 'output', multiple: false, required: false, valueType: null },
    ],
    meta: {},
  },
  {
    id: 'core.while',
    title: 'While',
    description: 'Цикл с проверкой условия.',
    kind: 'while',
    configurable: true,
    inputPorts: [{ id: 'in', label: 'Вход', direction: 'input', multiple: false, required: true, valueType: null }],
    outputPorts: [
      { id: 'loop', label: 'Цикл', direction: 'output', multiple: false, required: false, valueType: null },
      { id: 'done', label: 'Готово', direction: 'output', multiple: false, required: false, valueType: null },
    ],
    meta: {},
  },
  {
    id: 'core.parallel',
    title: 'Параллельное выполнение',
    description: 'Параллельное разделение потока на ветви.',
    kind: 'parallel',
    configurable: true,
    inputPorts: [{ id: 'in', label: 'Вход', direction: 'input', multiple: false, required: true, valueType: null }],
    outputPorts: [
      { id: 'branch-1', label: 'Ветка 1', direction: 'output', multiple: false, required: false, valueType: null },
      { id: 'branch-2', label: 'Ветка 2', direction: 'output', multiple: false, required: false, valueType: null },
    ],
    meta: {},
  },
]
