import type { WidgetDefinition } from '@/components/layouts/grid'

import { markRaw } from 'vue'

import Agent_Widget from '@/features/endge-ide/ui/widgets/Agent_Widget.vue'
import Demonstration_Widget from '@/features/endge-ide/ui/widgets/Demonstration_Widget.vue'
import Domain_Widget from '@/features/endge-ide/ui/widgets/Domain_Widget.vue'
import Errors_Widget from '@/features/endge-ide/ui/widgets/Errors_Widget.vue'
import Events_Widget from '@/features/endge-ide/ui/widgets/Events_Widget.vue'
import Help_Widget from '@/features/endge-ide/ui/widgets/Help_Widget.vue'
import Inspector_Widget from '@/features/endge-ide/ui/widgets/Inspector_Widget.vue'
import Pulse_Widget from '@/features/endge-ide/ui/widgets/Pulse_Widget.vue'
import Raph_Widget from '@/features/endge-ide/ui/widgets/Raph_Widget.vue'
import Settings_Widget from '@/features/endge-ide/ui/widgets/Settings_Widget.vue'
import Storage_Widget from '@/features/endge-ide/ui/widgets/Storage_Widget.vue'
import Testing_Widget from '@/features/endge-ide/ui/widgets/Testing_Widget.vue'
import Versions_Widget from '@/features/endge-ide/ui/widgets/Versions_Widget.vue'
import UIEditorLibrary_Widget from '@/features/endge-admin-ui-editor/ui/UIEditorLibrary_Widget.vue'

export const endgeIDEWidgetsConfig: WidgetDefinition[] = [
  {
    id: 'project',
    title: 'Проект',
    icon: 'FolderTree',
    content: 'component',
    defaultComponent: markRaw(Domain_Widget),
    singleton: true,
    defaultPosition: 'left',
    allowedPositions: ['left', 'right', 'floating'],
    floatingConstraints: {
      minWidth: 250,
      maxWidth: 500,
      minHeight: 300,
      maxHeight: 600,
      defaultWidth: 300,
      defaultHeight: 400,
    },
  },
  {
    id: 'inspector',
    title: 'Инспектор',
    icon: 'Glasses',
    content: 'component',
    defaultComponent: markRaw(Inspector_Widget),
    singleton: true,
    defaultPosition: 'right',
    allowedPositions: ['left', 'right', 'floating'],
    floatingConstraints: {
      minWidth: 300,
      maxWidth: 600,
      minHeight: 400,
      maxHeight: 800,
      defaultWidth: 400,
      defaultHeight: 600,
    },
  },
  {
    id: 'versions',
    title: 'Версии',
    icon: 'GitBranch',
    content: 'component',
    defaultComponent: markRaw(Versions_Widget),
    singleton: true,
    defaultPosition: 'left',
    allowedPositions: ['left', 'right', 'floating'],
    floatingConstraints: {
      minWidth: 250,
      maxWidth: 500,
      minHeight: 300,
      maxHeight: 600,
      defaultWidth: 300,
      defaultHeight: 400,
    },
  },
  {
    id: 'settings',
    title: 'Настройки',
    icon: 'Settings',
    content: 'component',
    defaultComponent: markRaw(Settings_Widget),
    singleton: true,
    defaultPosition: 'left',
    allowedPositions: ['left', 'right', 'floating'],
    floatingConstraints: {
      minWidth: 250,
      maxWidth: 500,
      minHeight: 300,
      maxHeight: 600,
      defaultWidth: 300,
      defaultHeight: 400,
    },
  },
  {
    id: 'ui-library',
    title: 'UI Library',
    icon: 'LibraryBig',
    content: 'component',
    defaultComponent: markRaw(UIEditorLibrary_Widget),
    singleton: true,
    defaultPosition: 'left',
    allowedPositions: ['left', 'right', 'floating'],
    floatingConstraints: {
      minWidth: 250,
      maxWidth: 520,
      minHeight: 300,
      maxHeight: 900,
      defaultWidth: 320,
      defaultHeight: 540,
    },
  },
  {
    id: 'errors',
    title: 'Ошибки',
    icon: 'ShieldAlert',
    content: 'component',
    defaultComponent: markRaw(Errors_Widget),
    singleton: true,
    defaultPosition: 'bottom',
    allowedPositions: ['bottom', 'left', 'right', 'floating'],
    floatingConstraints: {
      minWidth: 300,
      maxWidth: 800,
      minHeight: 200,
      maxHeight: 500,
      defaultWidth: 600,
      defaultHeight: 300,
    },
  },
  // {
  //   id: 'terminal',
  //   title: 'Терминал',
  //   icon: 'Terminal',
  //   content: 'component',
  //   defaultComponent: markRaw(Terminal_Widget),
  //   singleton: true,
  //   defaultPosition: 'bottom',
  //   allowedPositions: ['bottom', 'left', 'right', 'floating'],
  //   floatingConstraints: {
  //     minWidth: 300,
  //     maxWidth: 800,
  //     minHeight: 200,
  //     maxHeight: 500,
  //     defaultWidth: 600,
  //     defaultHeight: 300,
  //   },
  // },
  {
    id: 'storage',
    title: 'Локальное хранилище',
    icon: 'Database',
    content: 'component',
    defaultComponent: markRaw(Storage_Widget),
    singleton: true,
    defaultPosition: 'right',
    allowedPositions: ['left', 'right', 'floating'],
    floatingConstraints: {
      minWidth: 300,
      maxWidth: 600,
      minHeight: 400,
      maxHeight: 800,
      defaultWidth: 400,
      defaultHeight: 600,
    },
  },
  {
    id: 'testing',
    title: 'Тестирование',
    icon: 'Microscope',
    content: 'component',
    defaultComponent: markRaw(Testing_Widget),
    singleton: true,
    defaultPosition: 'right',
    allowedPositions: ['left', 'right', 'floating'],
    floatingConstraints: {
      minWidth: 300,
      maxWidth: 600,
      minHeight: 400,
      maxHeight: 800,
      defaultWidth: 400,
      defaultHeight: 600,
    },
  },
  {
    id: 'events',
    title: 'События',
    icon: 'Activity',
    content: 'component',
    defaultComponent: markRaw(Events_Widget),
    singleton: true,
    defaultPosition: 'right',
    allowedPositions: ['left', 'right', 'floating'],
    floatingConstraints: {
      minWidth: 300,
      maxWidth: 600,
      minHeight: 400,
      maxHeight: 800,
      defaultWidth: 400,
      defaultHeight: 600,
    },
  },
  {
    id: 'pulse',
    title: 'Пульс',
    icon: 'HeartPulse',
    content: 'component',
    defaultComponent: markRaw(Pulse_Widget),
    singleton: true,
    defaultPosition: 'right',
    allowedPositions: ['left', 'right', 'floating'],
    floatingConstraints: {
      minWidth: 320,
      maxWidth: 640,
      minHeight: 360,
      maxHeight: 900,
      defaultWidth: 420,
      defaultHeight: 640,
    },
  },
  {
    id: 'raph',
    title: 'Raph',
    icon: 'Zap',
    content: 'component',
    defaultComponent: markRaw(Raph_Widget),
    singleton: true,
    defaultPosition: 'right',
    allowedPositions: ['left', 'right', 'floating'],
    floatingConstraints: {
      minWidth: 300,
      maxWidth: 600,
      minHeight: 400,
      maxHeight: 800,
      defaultWidth: 400,
      defaultHeight: 600,
    },
  },
  {
    id: 'help',
    title: 'Документация',
    icon: 'LifeBuoy',
    content: 'component',
    defaultComponent: markRaw(Help_Widget),
    singleton: true,
    defaultPosition: 'right',
    allowedPositions: ['left', 'right', 'floating'],
    floatingConstraints: {
      minWidth: 300,
      maxWidth: 600,
      minHeight: 400,
      maxHeight: 800,
      defaultWidth: 400,
      defaultHeight: 600,
    },
  },
  {
    id: 'agent',
    title: 'Агент',
    icon: 'Bot',
    content: 'component',
    defaultComponent: markRaw(Agent_Widget),
    singleton: true,
    defaultPosition: 'right',
    allowedPositions: ['left', 'right', 'floating'],
    floatingConstraints: {
      minWidth: 320,
      maxWidth: 600,
      minHeight: 400,
      maxHeight: 800,
      defaultWidth: 420,
      defaultHeight: 560,
    },
  },
  {
    id: 'demonstration',
    title: 'Демонстрация',
    icon: 'ScanEye',
    content: 'component',
    defaultComponent: markRaw(Demonstration_Widget),
    singleton: true,
    defaultPosition: 'floating',
    allowedPositions: ['left', 'right', 'floating'],
    floatingConstraints: {
      minWidth: 320,
      maxWidth: 1920,
      minHeight: 200,
      maxHeight: 1200,
      defaultWidth: 500,
      defaultHeight: 320,
    },
  },
]
